development:
  adapter: postgresql
  database: tranquil_falls_2379_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: tranquil_falls_2379_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: tranquil_falls_2379_production
  pool: 5
  timeout: 5000
